# Generated by Django 3.0.8 on 2020-09-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0008_auto_20200630_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='facebook',
            new_name='codeforces',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dob',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hacker_rank',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='uva',
            field=models.URLField(blank=True),
        ),
    ]
