# Generated by Django 3.0.8 on 2020-09-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0009_auto_20200914_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='codeforces',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='hacker_rank',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='uva',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='codeforces_username',
            field=models.CharField(default='abc', max_length=250),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='uva_id',
            field=models.CharField(default='11', max_length=250),
        ),
    ]
