# Generated by Django 3.0.8 on 2020-09-28 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_Post', '0002_auto_20200702_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='OJStanding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uva_id', models.CharField(blank=True, max_length=250)),
                ('uva_ranking', models.CharField(blank=True, max_length=250)),
                ('uva_submission', models.CharField(blank=True, max_length=250)),
                ('codeforces_username', models.CharField(blank=True, max_length=250)),
                ('codeforces_ranking', models.CharField(blank=True, max_length=250)),
                ('codeforces_submission', models.CharField(blank=True, max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
