# Generated by Django 3.0.8 on 2020-09-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Post', '0003_ojstanding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ojstanding',
            name='codeforces_ranking',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ojstanding',
            name='codeforces_submission',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ojstanding',
            name='codeforces_username',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ojstanding',
            name='uva_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ojstanding',
            name='uva_ranking',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ojstanding',
            name='uva_submission',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
