# Generated by Django 3.0.8 on 2020-09-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Post', '0005_ojstanding_uva_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='ojstanding',
            name='codeforces_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
