# Generated by Django 3.0.8 on 2020-09-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Post', '0006_ojstanding_codeforces_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ojstanding',
            name='codeforces_submission',
            field=models.CharField(blank=True, default=0, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ojstanding',
            name='uva_submission',
            field=models.CharField(blank=True, default=0, max_length=250, null=True),
        ),
    ]
