# Generated by Django 3.0.8 on 2020-09-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Post', '0008_auto_20200928_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='ojstanding',
            name='total_submission',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ojstanding',
            name='codeforces_submission',
            field=models.CharField(blank=True, default=10, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ojstanding',
            name='uva_submission',
            field=models.CharField(blank=True, default=10, max_length=250, null=True),
        ),
    ]
