# Generated by Django 3.0.8 on 2020-09-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Post', '0009_auto_20200928_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ojstanding',
            name='total_submission',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
